[2021-12-11 14:05:13,929] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: dag_postgres_create_table.make_a_staging_table 2021-12-11T14:05:12.607786+00:00 [queued]>
[2021-12-11 14:05:13,941] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: dag_postgres_create_table.make_a_staging_table 2021-12-11T14:05:12.607786+00:00 [queued]>
[2021-12-11 14:05:13,942] {taskinstance.py:1087} INFO - 
--------------------------------------------------------------------------------
[2021-12-11 14:05:13,943] {taskinstance.py:1088} INFO - Starting attempt 1 of 1
[2021-12-11 14:05:13,944] {taskinstance.py:1089} INFO - 
--------------------------------------------------------------------------------
[2021-12-11 14:05:13,958] {taskinstance.py:1107} INFO - Executing <Task(PostgresOperator): make_a_staging_table> on 2021-12-11T14:05:12.607786+00:00
[2021-12-11 14:05:13,964] {standard_task_runner.py:52} INFO - Started process 108 to run task
[2021-12-11 14:05:13,970] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'dag_postgres_create_table', 'make_a_staging_table', '2021-12-11T14:05:12.607786+00:00', '--job-id', '2', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/dag_postgres_create_table.py', '--cfg-path', '/tmp/tmpsyxz5d53', '--error-file', '/tmp/tmp6_3so2di']
[2021-12-11 14:05:13,972] {standard_task_runner.py:77} INFO - Job 2: Subtask make_a_staging_table
[2021-12-11 14:05:14,019] {logging_mixin.py:104} INFO - Running <TaskInstance: dag_postgres_create_table.make_a_staging_table 2021-12-11T14:05:12.607786+00:00 [running]> on host 13f30f6f46b4
[2021-12-11 14:05:14,074] {taskinstance.py:1302} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=dag_postgres_create_table
AIRFLOW_CTX_TASK_ID=make_a_staging_table
AIRFLOW_CTX_EXECUTION_DATE=2021-12-11T14:05:12.607786+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-12-11T14:05:12.607786+00:00
[2021-12-11 14:05:14,076] {postgres.py:68} INFO - Executing: CREATE TABLE scaled_data
    (
        idx_col integer,
        petal_width float,
        petal_length float
    );
    
[2021-12-11 14:05:14,100] {taskinstance.py:1501} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1157, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1331, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1361, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/postgres/operators/postgres.py", line 70, in execute
    self.hook.run(self.sql, self.autocommit, parameters=self.parameters)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/hooks/dbapi.py", line 177, in run
    with closing(self.get_conn()) as conn:
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/postgres/hooks/postgres.py", line 88, in get_conn
    conn = deepcopy(self.connection or self.get_connection(conn_id))
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/hooks/base.py", line 67, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/connection.py", line 379, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `postgres_source` isn't defined
[2021-12-11 14:05:14,106] {taskinstance.py:1551} INFO - Marking task as FAILED. dag_id=dag_postgres_create_table, task_id=make_a_staging_table, execution_date=20211211T140512, start_date=20211211T140513, end_date=20211211T140514
[2021-12-11 14:05:14,146] {local_task_job.py:149} INFO - Task exited with return code 1
